name: Awesome CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Building project with Gradle
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew build -x test

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - uses: actions/checkout@v2

        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Testing
          working-directory: .
          run: |
            chmod +x gradlew
            ./gradlew test
